insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (1, 'Barrio Córdoba');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (2, 'Ciudadela Universitaria Manta');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (3, 'Barrio del Centro Manta');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (4, 'El Palmar');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (5, 'Los Esteros');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (6, 'Andrés de Vera');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (7, 'Ciudadela los Tamarindos');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (8, 'Ciudadela  Universitaria Portoviejo');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (9, 'Alajuela');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (10, 'Barrio Centro Portoviejo');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (11, 'La Alborada');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (12, 'Los Sacuces');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (13, 'Samanes');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (14, 'Urdesa Central');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (15, 'Los Ceibos');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (16, 'La Carolina');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (17, 'Cumbayá');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (18, 'Carcelén');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (19, 'El Rosario');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (20, 'La Ferroviaria');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (21, 'Juan Leon Mera');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (22, 'San Antonio');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (23, 'Izamba');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (24, 'La Floresta');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (25, 'La Florida');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (26, 'Barrio Juan de la Cruz');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (27, 'La Union');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (28, 'Lomas');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (29, 'Barrio Amazonas');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (30, 'Los Canelos');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (31, 'Ahuano');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (32, 'Los pinos');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (33, 'San Jacinto');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (34, 'Las Palmas');
insert into grupo_poblacion (poblacion_id, poblacion_nombre) values (35, 'Santa Ines');

