insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (1, 4, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (1, 13, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (2, 8, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (2, 18, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (2, 20, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (2, 31, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (2, 50, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (3, 29, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (3, 43, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (3, 55, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (4, 5, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (4, 17, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (4, 26, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (4, 32, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (4, 51, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (5, 43, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (5, 54, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (5, 55, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (6, 7, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (6, 10, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (6, 22, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (6, 46, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (6, 47, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (7, 29, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (7, 38, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (7, 54, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (8, 4, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (8, 23, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (8, 53, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (8, 14, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 3, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 10, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 11, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 19, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 28, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (9, 44, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (10, 15, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (10, 24, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (10, 33, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (10, 48, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (10, 52, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 1, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 6, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 12, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 30, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 36, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (11, 39, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (12, 16, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (12, 27, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (12, 35, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (12, 49, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (13, 29, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (13, 43, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (13, 55, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (14, 6, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (14, 12, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (14, 30, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (14, 34, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (14, 41, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (15, 2, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (15, 5, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (15, 17, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (15, 32, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (16, 38, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (16, 54, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (17, 16, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (17, 25, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (17, 27, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (17, 35, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (17, 49, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (18, 9, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (18, 15, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (18, 31, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (18, 50, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (19, 18, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (19, 33, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (19, 48, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (19, 52, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (20, 25, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (20, 49, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 3, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 7, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 28, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 44, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 46, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (21, 47, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (22, 2, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (22, 17, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (22, 32, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (22, 40, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (23, 4, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (23, 13, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (23, 23, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (23, 37, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (23, 53, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (24, 9, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (24, 15, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (24, 20, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (24, 24, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (24, 31, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (25, 8, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (25, 18, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (25, 33, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (25, 50, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (25, 52, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (26, 13, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (26, 14, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (26, 37, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (27, 16, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (27, 25, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (27, 27, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (27, 35, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (28, 29, 'Empelado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (28, 38, 'Empelado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (28, 43, 'Empelado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (28, 54, 'Empelado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (28, 55, 'Empelado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (29, 26, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (29, 32, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (29, 51, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (30, 25, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (30, 27, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (30, 49, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (31, 1, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (31, 6, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (31, 12, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (31, 39, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (31, 45, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (32, 16, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (32, 35, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (32, 49, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (33, 40, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (33, 42, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (33, 51, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (34, 23, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (34, 37, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (34, 53, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (35, 34, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (35, 36, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (35, 41, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (35, 45, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (36, 16, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (36, 27, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (36, 35, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (37, 2, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (37, 5, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (37, 26, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (38, 1, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (38, 30, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (38, 34, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (38, 41, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (38, 45, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (39, 40, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (39, 42, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (39, 51, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (40, 4, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (40, 14, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (40, 37, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (40, 53, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (41, 32, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (41, 42, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (42, 35, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (42, 49, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (43, 2, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (43, 5, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (44, 9, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (44, 21, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (44, 33, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (44, 48, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (45, 8, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (45, 20, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (45, 21, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (45, 50, 'Empelado temporal');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 3, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 7, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 11, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 19, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 22, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (46, 44, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (47, 18, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (47, 21, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (47, 52, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (47, 55, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (48, 17, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (48, 40, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (48, 51, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (49, 9, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (49, 24, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (49, 31, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (49, 48, 'Empleado por Contrato');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (50, 2, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (50, 26, 'Empleado Permanente');
insert into encuesta_personal (personal_id, encuesta_id, tipo_personal) values (50, 42, 'Empleado Permanente');
